// Package xrpc implements a lightweight customizable XRPC [Client].
//
// The [Client] can be used to perform [Client.Query] and [Client.Procedure].
// This returns an [ErrResponse] if the status code is invalid.
//
// # Errors
//
// [ErrResponse] is a generic error returned by the [Client]: it contains the response's status code and body.
// It can be converted into an [ErrStandardResponse] with [errors.AsType] if the API returns a standard error response:
//
//	var err xrpc.ErrResponse
//	if e, ok := errors.AsType[xrpc.ErrStandardResponse](err); ok {
//	  // e is a valid ErrStandardResponse
//	}
//
// An [ErrStandardResponse] wraps an [ErrStandard] (defined by the lexicon) and a specific message.
// The [ErrStandard] contained can be checked with [errors.Is], got with [errors.AsType] and unwrapped with
// [errors.Unwrap].
// You can directly check the [ErrStandard] on [ErrResponse] with [errors.Is] and [errors.AsType].
//
// The [ErrStandardResponse] already wraps the [ErrStandard]: you can use [errors.Unwrap] to get it.
//
// # Record
//
// You can use the [Record] interface to define records:
//
//	var CollectionMyRecord = atproto.NewNSIDBuilder("org.example").Name("myRecord").Build()
//
//	type MyRecord struct {
//	  Foo string `json:"bar"`
//	}
//
//	func (r *MyRecord) Collection() *atproto.NSID {
//	  return CollectionMyRecord
//	}
//
// This interface can be used with predefined XRPC functions, like [GetRecord] or [ListRecords].
//
// When your [Record] is sent, it is firstly marshaled into a map with [MarshalToMap] and then marshaled into JSON with
// [json.Marshal].
// If your [Record] requires a custom logic to be marshaled, it must implement [MapMarshaler] and returns a
// map[string]any.
// If you define custom objects, it can return anything.
//
// When your [Record] is received, it is unmarshaled with [json.Unmarshal].
// If it requires a custom logic, you must implement [json.Unmarshaler].
//
// If you want to marshal your [Record] into a JSON, you must use [Marshal].
//
// Sometimes, you must represent an absence of response and a null element.
// [Nullable] is a wrapper that can be used to represent these values.
//
// # Auth
//
// Some endpoint requires [Auth].
// The [AuthClient] is used to authentificate your requests.
// Currently, only auth using JWT is supported.
//
// You can get a new [AuthClient] using [JWTAuth] with the subpackage [xrpc/server].
//
// # Compatibility with Indigo
//
// XRPC provides [CompatClient], a [Client] that is compatible with lexicons generated by Indigo.
// It can be safely used as a LexClient while remaining a full [Client].
//
// If you want to use [Auth] with [CompatClient], create a new [AuthClient] and pass it to [NewCompatClient].
// All requests sent by [CompatClient] will be authentificated, including them sent by Indigo.
package xrpc
